-- Permission templates ("profiles"): a Membership points at one template, and the
-- template's permission set IS the member's authorization. See permissions.prisma
-- and src/modules/settings/organization/permission-templates/.
--
-- The Owner template (is_owner) stores NO permission keys — it is resolved to the
-- full code catalog at runtime, so a permission shipped later needs no backfill.

-- 1. Schema (generated by `prisma migrate diff`) -----------------------------

-- AlterTable
ALTER TABLE "memberships" ADD COLUMN     "permission_template_id" UUID;

-- CreateTable
CREATE TABLE "permission_templates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255),
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "is_owner" BOOLEAN NOT NULL DEFAULT false,
    "permissions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "permission_templates_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "permission_templates_organization_id_is_deleted_idx" ON "permission_templates"("organization_id", "is_deleted");

-- CreateIndex
CREATE UNIQUE INDEX "permission_templates_organization_id_name_key" ON "permission_templates"("organization_id", "name");

-- AddForeignKey
ALTER TABLE "permission_templates" ADD CONSTRAINT "permission_templates_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "permission_templates" ADD CONSTRAINT "permission_templates_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "permission_templates" ADD CONSTRAINT "permission_templates_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_permission_template_id_fkey" FOREIGN KEY ("permission_template_id") REFERENCES "permission_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 2. Backfill existing organizations ------------------------------------------
-- Every org gets the three immutable system templates, and every existing
-- membership is pointed at the one matching its legacy `role`. Guarded so the
-- migration is safe to re-run. Migrations run as the table owner (bypasses RLS),
-- so these writes are allowed without app.current_tenant. The permission lists
-- below are a point-in-time SNAPSHOT of permissions.catalog.ts — that is correct:
-- a migration is frozen history, not a live import of app code.

-- Owner — no keys stored; is_owner grants everything, computed at runtime.
INSERT INTO "permission_templates" (organization_id, name, description, is_system, is_owner, permissions)
SELECT o.id, 'Owner', 'Full access to everything. Cannot be edited or deleted.', true, true, ARRAY[]::text[]
FROM "organizations" o
WHERE NOT EXISTS (
  SELECT 1 FROM "permission_templates" pt WHERE pt.organization_id = o.id AND pt.name = 'Owner'
);

-- Admin — everything except organization:delete and role:manage.
INSERT INTO "permission_templates" (organization_id, name, description, is_system, is_owner, permissions)
SELECT o.id, 'Admin',
  'Manage all data and settings, except deleting the organization or editing roles.',
  true, false,
  ARRAY[
    'vendor:read','vendor:create','vendor:update','vendor:delete',
    'item:read','item:create','item:update','item:delete',
    'currency:read','currency:manage',
    'uom:read','uom:manage',
    'custom_field:read','custom_field:manage',
    'member:read','member:manage',
    'role:read',
    'organization:read','organization:update'
  ]::text[]
FROM "organizations" o
WHERE NOT EXISTS (
  SELECT 1 FROM "permission_templates" pt WHERE pt.organization_id = o.id AND pt.name = 'Admin'
);

-- Member — read-only across every module.
INSERT INTO "permission_templates" (organization_id, name, description, is_system, is_owner, permissions)
SELECT o.id, 'Member', 'Read-only access across all modules.', true, false,
  ARRAY[
    'vendor:read','item:read','currency:read','uom:read',
    'custom_field:read','member:read','role:read','organization:read'
  ]::text[]
FROM "organizations" o
WHERE NOT EXISTS (
  SELECT 1 FROM "permission_templates" pt WHERE pt.organization_id = o.id AND pt.name = 'Member'
);

-- Link each existing membership to the seeded template matching its legacy role.
UPDATE "memberships" m
SET permission_template_id = pt.id
FROM "permission_templates" pt
WHERE pt.organization_id = m.organization_id
  AND pt.name = CASE lower(m.role)
                  WHEN 'owner' THEN 'Owner'
                  WHEN 'admin' THEN 'Admin'
                  ELSE 'Member'
                END
  AND m.permission_template_id IS NULL;

-- 3. Row-Level Security -------------------------------------------------------
-- permission_templates is a tenant table. Copied from the enable_rls migration.
-- The app connects as `jobwork_app` (non-owner) so this is enforced; runAsTenant
-- sets app.current_tenant. Added to TENANT_TABLES in src/db/rls.test.ts.
ALTER TABLE "permission_templates" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "permission_templates"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
