-- add_job_order_step_input_batches
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
-- CreateTable
-- RLS is enabled at the bottom of this file, and the table is registered in
-- TENANT_TABLES (src/db/rls.test.ts). Both were required before promoting.
CREATE TABLE "job_order_step_input_batches" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "job_order_step_input_id" UUID NOT NULL,
    "batch_id" UUID NOT NULL,
    "location_id" UUID NOT NULL,
    "qty" DECIMAL(18,4) NOT NULL,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_order_step_input_batches_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "job_order_step_input_batches_organization_id_job_order_step_idx" ON "job_order_step_input_batches"("organization_id", "job_order_step_input_id");

-- CreateIndex
CREATE INDEX "job_order_step_input_batches_organization_id_batch_id_idx" ON "job_order_step_input_batches"("organization_id", "batch_id");

-- CreateIndex
-- REVIEWED [ADD UNIQUE]: the table is created empty by this same migration, so
-- there are no existing rows to collide. The soft-delete caveat is real and is
-- handled in the service: `plannedBatches` are REPLACED on every job order save
-- (hard delete, then re-insert), because a plan is a statement of current intent
-- with no history worth keeping — unlike the documents that move stock. So a
-- soft-deleted row can never sit on this key.
CREATE UNIQUE INDEX "job_order_step_input_batches_job_order_step_input_id_batch__key" ON "job_order_step_input_batches"("job_order_step_input_id", "batch_id", "location_id");

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_job_order_step_input_id_fkey" FOREIGN KEY ("job_order_step_input_id") REFERENCES "job_order_step_inputs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_input_batches" ADD CONSTRAINT "job_order_step_input_batches_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- RowLevelSecurity
--
-- 🔴 A tenant table with no policy is unprotected and nothing will tell you
-- (CLAUDE.md). This table carries its own `organization_id`, so it takes the
-- direct form — the same two statements as `job_issue_lines` in
-- 20260805070926_jobwork_sprints_2_to_4, not the join-through-parent form the
-- `*_activities` tables need.
ALTER TABLE "job_order_step_input_batches" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "job_order_step_input_batches"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
