-- multi_item_steps
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
-- 🔴 TWO `DROP INDEX` STATEMENTS WERE REMOVED FROM THIS DRAFT BY HAND.
--
-- `migrate diff` wanted to drop `permission_templates_organization_id_name_key`
-- and `roles_organization_id_name_key`. Those are the PARTIAL unique indexes
-- shipped on 2026-08-05 (migrations 20260805130000 and 20260805133000):
--
--     CREATE UNIQUE INDEX ... ON roles (organization_id, name) WHERE is_deleted = false
--
-- Prisma cannot express a partial index, so its `@@unique` renders as the plain
-- one and every future diff will keep asking to "fix" the difference. Applying
-- that would silently undo the soft-delete-aware uniqueness those migrations
-- exist for — a deleted role's name would occupy the key forever again.
--
-- They are unrelated to this change. Strip them from every future draft too.

-- AlterTable
ALTER TABLE "job_issue_lines" ADD COLUMN     "item_id" UUID,
ADD COLUMN     "uom_id" UUID;

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "route_step_inputs" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "route_step_inputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "route_step_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "route_step_inputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "route_step_outputs" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "route_step_outputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "route_step_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "route_step_outputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "job_order_step_inputs" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "job_order_step_inputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "job_order_step_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "planned_qty" DECIMAL(18,4),
    "from_stock" BOOLEAN NOT NULL DEFAULT false,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_order_step_inputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "job_order_step_outputs" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "job_order_step_outputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "job_order_step_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "expected_qty" DECIMAL(18,4),
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_order_step_outputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "job_receipt_outputs" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "job_receipt_outputs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "job_receipt_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "received_qty" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "accepted_qty" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "rework_qty" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "scrap_qty" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "returned_qty" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "value_share" DECIMAL(18,4),
    "output_lot_id" UUID,
    "rework_lot_id" UUID,
    "parent_package_id" UUID,
    "reason_id" UUID,
    "responsibility" VARCHAR(20),
    "remarks" TEXT,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "job_receipt_outputs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "route_step_inputs_organization_id_route_step_id_idx" ON "route_step_inputs"("organization_id", "route_step_id");

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "route_step_inputs_route_step_id_item_id_key" ON "route_step_inputs"("route_step_id", "item_id");

-- CreateIndex
CREATE INDEX "route_step_outputs_organization_id_route_step_id_idx" ON "route_step_outputs"("organization_id", "route_step_id");

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "route_step_outputs_route_step_id_item_id_key" ON "route_step_outputs"("route_step_id", "item_id");

-- CreateIndex
CREATE INDEX "job_order_step_inputs_organization_id_job_order_step_id_idx" ON "job_order_step_inputs"("organization_id", "job_order_step_id");

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "job_order_step_inputs_job_order_step_id_item_id_key" ON "job_order_step_inputs"("job_order_step_id", "item_id");

-- CreateIndex
CREATE INDEX "job_order_step_outputs_organization_id_job_order_step_id_idx" ON "job_order_step_outputs"("organization_id", "job_order_step_id");

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "job_order_step_outputs_job_order_step_id_item_id_key" ON "job_order_step_outputs"("job_order_step_id", "item_id");

-- CreateIndex
CREATE INDEX "job_receipt_outputs_organization_id_job_receipt_id_idx" ON "job_receipt_outputs"("organization_id", "job_receipt_id");

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_route_step_id_fkey" FOREIGN KEY ("route_step_id") REFERENCES "route_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_inputs" ADD CONSTRAINT "route_step_inputs_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_route_step_id_fkey" FOREIGN KEY ("route_step_id") REFERENCES "route_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "route_step_outputs" ADD CONSTRAINT "route_step_outputs_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_job_order_step_id_fkey" FOREIGN KEY ("job_order_step_id") REFERENCES "job_order_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_inputs" ADD CONSTRAINT "job_order_step_inputs_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_job_order_step_id_fkey" FOREIGN KEY ("job_order_step_id") REFERENCES "job_order_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_order_step_outputs" ADD CONSTRAINT "job_order_step_outputs_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_issue_lines" ADD CONSTRAINT "job_issue_lines_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_issue_lines" ADD CONSTRAINT "job_issue_lines_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_job_receipt_id_fkey" FOREIGN KEY ("job_receipt_id") REFERENCES "job_receipts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_output_lot_id_fkey" FOREIGN KEY ("output_lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_rework_lot_id_fkey" FOREIGN KEY ("rework_lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_parent_package_id_fkey" FOREIGN KEY ("parent_package_id") REFERENCES "lot_packages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_reason_id_fkey" FOREIGN KEY ("reason_id") REFERENCES "rejection_reasons"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_receipt_outputs" ADD CONSTRAINT "job_receipt_outputs_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- ROW-LEVEL SECURITY — five new tenant tables
-- ---------------------------------------------------------------------------
-- Copied from migrations/20260716183126_enable_rls. A tenant table with no
-- policy is unprotected and nothing will warn you, which is why each of these
-- also goes into TENANT_TABLES in src/db/rls.test.ts in the same change.
--
-- Every one of these carries its OWN organization_id rather than reaching its
-- parent through a join, for exactly the reason lot_packages does: a policy that
-- depends on a join is one forgotten join away from returning another tenant's
-- rows.

ALTER TABLE "route_step_inputs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "route_step_inputs"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

ALTER TABLE "route_step_outputs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "route_step_outputs"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

ALTER TABLE "job_order_step_inputs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "job_order_step_inputs"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

ALTER TABLE "job_order_step_outputs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "job_order_step_outputs"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

ALTER TABLE "job_receipt_outputs" ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "job_receipt_outputs"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

-- ---------------------------------------------------------------------------
-- BACKFILL — one row per old scalar column
-- ---------------------------------------------------------------------------
-- 🔴 This migration is ADDITIVE ONLY. The old columns
-- (route_steps.issue_item_id, job_order_steps.receive_item_id,
-- job_issues.item_id, job_receipts.output_item_id, …) all stay, and the code
-- that still reads them keeps working while this rolls out. Migration B drops
-- them, and only after the services and UI that read the new tables have
-- shipped — dropping them together means any instance still running the old
-- build 500s on every list query.
--
-- Runs as the migration role, which bypasses RLS, so no tenant scoping is
-- needed or possible here. organization_id is copied from the parent row.

-- Route step inputs: one per template step that named an issue item.
INSERT INTO "route_step_inputs" (organization_id, route_step_id, seq, item_id, uom_id)
SELECT organization_id, id, 1, issue_item_id, issue_uom_id
FROM   "route_steps"
WHERE  issue_item_id IS NOT NULL AND is_deleted = false;

-- Route step outputs. is_primary = true: a single output IS the primary one.
INSERT INTO "route_step_outputs" (organization_id, route_step_id, seq, item_id, uom_id, is_primary)
SELECT organization_id, id, 1, receive_item_id, receive_uom_id, true
FROM   "route_steps"
WHERE  receive_item_id IS NOT NULL AND is_deleted = false;

-- Job order step inputs. planned_input_qty was per STEP; with one input it is
-- that input's planned quantity. from_stock stays false: every one of these
-- came from a chain that the old hard rule had already validated.
INSERT INTO "job_order_step_inputs"
  (organization_id, job_order_step_id, seq, item_id, uom_id, planned_qty, from_stock)
SELECT organization_id, id, 1, issue_item_id, issue_uom_id, planned_input_qty, false
FROM   "job_order_steps"
WHERE  issue_item_id IS NOT NULL AND is_deleted = false;

INSERT INTO "job_order_step_outputs"
  (organization_id, job_order_step_id, seq, item_id, uom_id, is_primary)
SELECT organization_id, id, 1, receive_item_id, receive_uom_id, true
FROM   "job_order_steps"
WHERE  receive_item_id IS NOT NULL AND is_deleted = false;

-- Issue lines inherit the item their header named. Every existing line came
-- from a single-item challan, so the header IS that line's item.
UPDATE "job_issue_lines" l
SET    item_id = i.item_id,
       uom_id  = i.uom_id
FROM   "job_issues" i
WHERE  l.job_issue_id = i.id AND l.item_id IS NULL;

-- Receipt outputs: one row per receipt, carrying what the header said and the
-- totals it had already summed. value_share stays NULL — the primary output
-- takes the remainder, which for a single output is the whole pot.
INSERT INTO "job_receipt_outputs"
  (organization_id, job_receipt_id, seq, item_id, uom_id, is_primary,
   received_qty, accepted_qty, rework_qty, scrap_qty, returned_qty,
   output_lot_id, rework_lot_id)
SELECT organization_id, id, 1, output_item_id, output_uom_id, true,
       total_received_qty, total_accepted_qty, total_rework_qty, total_scrap_qty,
       total_returned_qty, output_lot_id, rework_lot_id
FROM   "job_receipts"
WHERE  is_deleted = false;
