-- align_schema
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 8 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
-- 🔴 BLOCKING [LIKELY RENAME] drops notes and adds remarks in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "customers" DROP COLUMN "notes",
ADD COLUMN     "remarks" TEXT;

-- AlterTable
-- ⚠️ REVIEW [COLUMN TYPE CHANGE] an in-place cast can fail outright or silently truncate (varchar(n), numeric precision)
-- 🔴 BLOCKING [LIKELY RENAME] drops images and adds images in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "items" ALTER COLUMN "front_image" SET DATA TYPE TEXT,
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "images",
ADD COLUMN     "images" TEXT[],
-- ⚠️ REVIEW [COLUMN TYPE CHANGE] an in-place cast can fail outright or silently truncate (varchar(n), numeric precision)
ALTER COLUMN "rear_image" SET DATA TYPE TEXT;

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "organizations" DROP COLUMN "logo_url";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "users" DROP COLUMN "avatar_url";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
-- 🔴 BLOCKING [LIKELY RENAME] drops notes and adds remarks in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "vendors" DROP COLUMN "notes",
ADD COLUMN     "remarks" TEXT;
