-- remove_max_users_limit
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 21 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_action_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_actor_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_recipient_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_user_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_request_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_user_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_current_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_process_version_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_requester_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "oauth_states" DROP CONSTRAINT "oauth_states_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "oauth_states" DROP CONSTRAINT "oauth_states_user_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_adjustment_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_batch_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_batch_unit_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_line_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_batches" DROP CONSTRAINT "stock_adjustment_batches_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "stock_adjustment_lines_adjustment_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "stock_adjustment_lines_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "stock_adjustment_lines_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "stock_adjustment_lines_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustment_lines" DROP CONSTRAINT "stock_adjustment_lines_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustments" DROP CONSTRAINT "stock_adjustments_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustments" DROP CONSTRAINT "stock_adjustments_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustments" DROP CONSTRAINT "stock_adjustments_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_adjustments" DROP CONSTRAINT "stock_adjustments_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_layer_revaluations" DROP CONSTRAINT "stock_layer_revaluations_layer_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_layer_revaluations" DROP CONSTRAINT "stock_layer_revaluations_ledger_entry_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_layer_revaluations" DROP CONSTRAINT "stock_layer_revaluations_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "zoho_integrations" DROP CONSTRAINT "zoho_integrations_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "zoho_integrations" DROP CONSTRAINT "zoho_integrations_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "zoho_integrations" DROP CONSTRAINT "zoho_integrations_updated_by_fkey";

-- DropIndex
DROP INDEX "idx_approval_process_admins_user";

-- DropIndex
DROP INDEX "idx_approval_request_approvers_stage";

-- DropIndex
DROP INDEX "idx_approval_request_approvers_user";

-- DropIndex
DROP INDEX "idx_approval_request_stages_req";

-- DropIndex
DROP INDEX "idx_approval_requests_process";

-- DropIndex
DROP INDEX "idx_approval_requests_requester";

-- AlterTable
-- ⚠️ REVIEW [COLUMN TYPE CHANGE] an in-place cast can fail outright or silently truncate (varchar(n), numeric precision)
ALTER TABLE "approval_history" ALTER COLUMN "event_type" SET DATA TYPE VARCHAR(50),
-- ⚠️ REVIEW [SET NOT NULL] fails if any existing row holds NULL — backfill first
ALTER COLUMN "metadata" SET NOT NULL,
ALTER COLUMN "metadata" SET DEFAULT '{}';

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
-- 🔴 BLOCKING [LIKELY RENAME] drops ip_address, user_agent and adds created_at, updated_at in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "approval_request_approvers" DROP COLUMN "ip_address",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "user_agent",
ADD COLUMN     "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
-- 🔴 BLOCKING [LIKELY RENAME] drops completed_at, started_at and adds created_at, updated_at in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "approval_request_stages" DROP COLUMN "completed_at",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "started_at",
ADD COLUMN     "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "name" SET DEFAULT 'Stage 1';

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
-- 🔴 BLOCKING [LIKELY RENAME] drops created_by, is_deleted, updated_by, record_id and adds record_id in one statement. If this is a rename, replace it with ALTER TABLE ... RENAME COLUMN, or ADD + UPDATE-backfill + DROP. As written the old values are simply gone
ALTER TABLE "approval_requests" DROP COLUMN "created_by",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "is_deleted",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "updated_by",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "record_id",
ADD COLUMN     "record_id" UUID NOT NULL,
ALTER COLUMN "record_title" SET DEFAULT '';

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "bills" DROP COLUMN "approval_status";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "organizations" DROP COLUMN "max_users_limit";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_action_executions";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_notifications";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "oauth_states";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "stock_adjustment_batches";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "stock_adjustment_lines";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "stock_adjustments";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "stock_layer_revaluations";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "zoho_integrations";

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "approval_executed_actions" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "approval_executed_actions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "request_id" UUID NOT NULL,
    "action_type" VARCHAR(50) NOT NULL,
    "trigger_event" VARCHAR(50) NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "error_message" TEXT,
    "executed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "approval_executed_actions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "idx_approval_exec_actions_req" ON "approval_executed_actions"("request_id", "status");

-- CreateIndex
CREATE INDEX "idx_approval_req_approvers_user" ON "approval_request_approvers"("organization_id", "user_id", "status");

-- CreateIndex
CREATE INDEX "idx_approval_req_stages_req" ON "approval_request_stages"("request_id", "stage_order", "status");

-- CreateIndex
CREATE INDEX "idx_approval_requests_record" ON "approval_requests"("organization_id", "module_id", "record_id", "status");

-- CreateIndex
CREATE INDEX "idx_approval_requests_status" ON "approval_requests"("organization_id", "status", "submitted_at");

-- AddForeignKey
ALTER TABLE "approval_processes" ADD CONSTRAINT "approval_processes_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_processes" ADD CONSTRAINT "approval_processes_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_processes" ADD CONSTRAINT "approval_processes_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_versions" ADD CONSTRAINT "approval_process_versions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_versions" ADD CONSTRAINT "approval_process_versions_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "approval_processes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_versions" ADD CONSTRAINT "approval_process_versions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_rules" ADD CONSTRAINT "approval_process_rules_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_rules" ADD CONSTRAINT "approval_process_rules_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "approval_processes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_rules" ADD CONSTRAINT "approval_process_rules_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_rules" ADD CONSTRAINT "approval_process_rules_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_stages" ADD CONSTRAINT "approval_stages_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_stages" ADD CONSTRAINT "approval_stages_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "approval_process_rules"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_stages" ADD CONSTRAINT "approval_stages_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_stages" ADD CONSTRAINT "approval_stages_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_actions" ADD CONSTRAINT "approval_actions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_actions" ADD CONSTRAINT "approval_actions_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "approval_process_rules"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_actions" ADD CONSTRAINT "approval_actions_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "approval_stages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_actions" ADD CONSTRAINT "approval_actions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_actions" ADD CONSTRAINT "approval_actions_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_admins" ADD CONSTRAINT "approval_process_admins_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_admins" ADD CONSTRAINT "approval_process_admins_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "approval_processes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_process_admins" ADD CONSTRAINT "approval_process_admins_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_requests" ADD CONSTRAINT "approval_requests_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_requests" ADD CONSTRAINT "approval_requests_process_id_fkey" FOREIGN KEY ("process_id") REFERENCES "approval_processes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_requests" ADD CONSTRAINT "approval_requests_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "approval_process_rules"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_requests" ADD CONSTRAINT "approval_requests_requester_id_fkey" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_stages" ADD CONSTRAINT "approval_request_stages_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_stages" ADD CONSTRAINT "approval_request_stages_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "approval_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_stages" ADD CONSTRAINT "approval_request_stages_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "approval_stages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_approvers" ADD CONSTRAINT "approval_request_approvers_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_approvers" ADD CONSTRAINT "approval_request_approvers_request_stage_id_fkey" FOREIGN KEY ("request_stage_id") REFERENCES "approval_request_stages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_request_approvers" ADD CONSTRAINT "approval_request_approvers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_history" ADD CONSTRAINT "approval_history_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_history" ADD CONSTRAINT "approval_history_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "approval_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_history" ADD CONSTRAINT "approval_history_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_executed_actions" ADD CONSTRAINT "approval_executed_actions_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approval_executed_actions" ADD CONSTRAINT "approval_executed_actions_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "approval_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;
