-- add_bill_items_indexes
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 15 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_action_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_action_executions" DROP CONSTRAINT "approval_action_executions_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_actions" DROP CONSTRAINT "approval_actions_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_actor_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_history" DROP CONSTRAINT "approval_history_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_recipient_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_notifications" DROP CONSTRAINT "approval_notifications_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_admins" DROP CONSTRAINT "approval_process_admins_user_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_rules" DROP CONSTRAINT "approval_process_rules_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_process_versions" DROP CONSTRAINT "approval_process_versions_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_processes" DROP CONSTRAINT "approval_processes_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_request_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_approvers" DROP CONSTRAINT "approval_request_approvers_user_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_request_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_request_stages" DROP CONSTRAINT "approval_request_stages_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_current_stage_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_process_version_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_requester_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_requests" DROP CONSTRAINT "approval_requests_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_rule_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "approval_stages" DROP CONSTRAINT "approval_stages_updated_by_fkey";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "refresh_tokens" DROP COLUMN "idp_session_id",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "idp_subject";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "users" DROP COLUMN "identity_user_id";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_action_executions";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_actions";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_history";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_notifications";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_process_admins";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_process_rules";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_process_versions";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_processes";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_request_approvers";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_request_stages";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_requests";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "approval_stages";

-- CreateIndex
CREATE INDEX "bill_items_bill_id_item_id_idx" ON "bill_items"("bill_id", "item_id");

-- CreateIndex
CREATE INDEX "bill_items_job_receipt_id_item_id_idx" ON "bill_items"("job_receipt_id", "item_id");
