-- add_partial_unique_index
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 19 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "items" DROP CONSTRAINT "items_stocking_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_job_issue_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_lot_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_lot_package_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issue_lines" DROP CONSTRAINT "job_issue_lines_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_destination_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_job_order_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_job_order_step_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_source_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_issues" DROP CONSTRAINT "job_issues_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_issue_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_issue_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_job_order_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_receive_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_receive_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_order_steps" DROP CONSTRAINT "job_order_steps_work_centre_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_input_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_input_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_route_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_orders" DROP CONSTRAINT "job_orders_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_job_issue_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_job_issue_line_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_job_receipt_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_parent_package_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_reason_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipt_lines" DROP CONSTRAINT "job_receipt_lines_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_job_order_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_job_order_step_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_output_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_output_lot_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_output_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_rework_lot_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "job_receipts" DROP CONSTRAINT "job_receipts_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "locations" DROP CONSTRAINT "locations_vendor_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lot_packages" DROP CONSTRAINT "lot_packages_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lot_packages" DROP CONSTRAINT "lot_packages_lot_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lot_packages" DROP CONSTRAINT "lot_packages_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lot_packages" DROP CONSTRAINT "lot_packages_parent_package_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lot_packages" DROP CONSTRAINT "lot_packages_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lots" DROP CONSTRAINT "lots_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lots" DROP CONSTRAINT "lots_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lots" DROP CONSTRAINT "lots_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lots" DROP CONSTRAINT "lots_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "lots" DROP CONSTRAINT "lots_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "processes" DROP CONSTRAINT "processes_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "processes" DROP CONSTRAINT "processes_default_issue_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "processes" DROP CONSTRAINT "processes_default_receive_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "processes" DROP CONSTRAINT "processes_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "processes" DROP CONSTRAINT "processes_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "rejection_reasons" DROP CONSTRAINT "rejection_reasons_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "rejection_reasons" DROP CONSTRAINT "rejection_reasons_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "rejection_reasons" DROP CONSTRAINT "rejection_reasons_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_issue_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_issue_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_process_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_receive_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_receive_uom_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_route_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "route_steps" DROP CONSTRAINT "route_steps_work_centre_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "routes" DROP CONSTRAINT "routes_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "routes" DROP CONSTRAINT "routes_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "routes" DROP CONSTRAINT "routes_updated_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_created_by_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_item_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_location_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_lot_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_lot_package_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_organization_id_fkey";

-- DropForeignKey
-- ⚠️ REVIEW [DROP CONSTRAINT] no data is lost, but a rule that was being enforced stops being enforced
ALTER TABLE "stock_ledger" DROP CONSTRAINT "stock_ledger_uom_id_fkey";

-- DropIndex
DROP INDEX "roles_organization_id_name_key";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "items" DROP COLUMN "default_route_id",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "lot_tracking",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "nature",
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
DROP COLUMN "stocking_uom_id";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "locations" DROP COLUMN "vendor_id";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "vendors" DROP COLUMN "vendor_types";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_issue_lines";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_issues";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_order_steps";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_orders";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_receipt_lines";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "job_receipts";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "lot_packages";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "lots";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "processes";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "rejection_reasons";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "route_steps";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "routes";

-- DropTable
-- 🔴 BLOCKING [DROP TABLE] destroys the table and every row in it — and takes its RLS policy and grants with it
DROP TABLE "stock_ledger";

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "roles_org_name_key" ON "roles"("organization_id", "name") WHERE ("is_deleted" = false);
