-- change_assembly_status
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 3 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- DropIndex
DROP INDEX "composite_item_components_composite_component_key";

-- DropIndex
DROP INDEX "lots_parent_lot_ids_idx";

-- AlterTable
ALTER TABLE "item_assemblies" ALTER COLUMN "status" SET DEFAULT 'assembled';

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "processes" DROP COLUMN "is_active";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "rejection_reasons" DROP COLUMN "is_active";

-- AlterTable
-- 🔴 BLOCKING [DROP COLUMN] destroys every value in that column; re-adding it later restores the column, not the data
ALTER TABLE "routes" DROP COLUMN "is_active";
