-- add_assembly_activities
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 3 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "item_assembly_activities" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "item_assembly_activities" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "assembly_id" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "performed_by" VARCHAR(255),
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_assembly_activities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "item_assembly_activities_assembly_id_idx" ON "item_assembly_activities"("assembly_id");

-- AddForeignKey
ALTER TABLE "item_assembly_activities" ADD CONSTRAINT "item_assembly_activities_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_activities" ADD CONSTRAINT "item_assembly_activities_assembly_id_fkey" FOREIGN KEY ("assembly_id") REFERENCES "item_assemblies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_activities" ADD CONSTRAINT "item_assembly_activities_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_activities" ADD CONSTRAINT "item_assembly_activities_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "item_assembly_activities" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant isolation" ON "item_assembly_activities"
  USING (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
  WITH CHECK (organization_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
