-- Add organizations.tax_id_value (GSTIN).
--
-- The schema files, the Prisma client, and both the create and update paths have
-- referenced `taxIdValue` for some time, but the column was never migrated onto
-- this database. Every read of an organization therefore failed with P2022
-- "column organizations.tax_id_value does not exist" — `findMany` selects all
-- scalars, so the whole organizations module was down, not just writes.
--
-- Nullable with no default: the value is a GSTIN, which most rows legitimately do
-- not have, and there is nothing sensible to backfill.
--
-- Deliberately does NOT drop `organizations.website`, which `migrate diff` pairs
-- with this add and labels a likely rename. It is not a rename — `website` is a
-- URL and `tax_id_value` is a tax registration number, so there is nothing to
-- carry across. `website` is empty on all 7 rows and can be dropped safely at any
-- time, but that is a separate decision from unbreaking this endpoint and is left
-- to whoever removed it from the schema files.
ALTER TABLE "organizations" ADD COLUMN "tax_id_value" TEXT;
