-- composite_items
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
-- DropIndex
DROP INDEX "permission_templates_organization_id_name_key";

-- DropIndex
DROP INDEX "roles_organization_id_name_key";

-- AlterTable
ALTER TABLE "stock_ledger" ADD COLUMN     "stock_effect" VARCHAR(20) NOT NULL DEFAULT 'both';

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "composite_item_components" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "composite_item_components" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "composite_item_id" UUID NOT NULL,
    "component_item_id" UUID NOT NULL,
    "qty_per_unit" DECIMAL(18,6) NOT NULL,
    "uom_id" UUID,
    "seq" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "composite_item_components_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "item_assemblies" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "item_assemblies" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "assembly_number" VARCHAR(50) NOT NULL,
    "direction" VARCHAR(20) NOT NULL DEFAULT 'assemble',
    "assembly_date" TIMESTAMPTZ(6) NOT NULL,
    "composite_item_id" UUID NOT NULL,
    "composite_uom_id" UUID,
    "qty" DECIMAL(18,4) NOT NULL,
    "composite_lot_id" UUID,
    "location_id" UUID NOT NULL,
    "additional_cost" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "component_value" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "total_value" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "ownership" VARCHAR(20) NOT NULL DEFAULT 'own',
    "owner_party_id" UUID,
    "status" VARCHAR(20) NOT NULL DEFAULT 'posted',
    "remarks" TEXT,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_assemblies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- ⚠️ REVIEW [TENANT TABLE WITHOUT RLS] "item_assembly_lines" has organization_id but this migration never enables RLS on it. Copy the policy statements from migrations/*_enable_rls and add it to TENANT_TABLES in src/db/rls.test.ts
CREATE TABLE "item_assembly_lines" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "organization_id" UUID NOT NULL,
    "assembly_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL DEFAULT 0,
    "item_id" UUID NOT NULL,
    "uom_id" UUID,
    "lot_id" UUID NOT NULL,
    "lot_package_id" UUID,
    "qty_per_unit" DECIMAL(18,6) NOT NULL,
    "qty" DECIMAL(18,4) NOT NULL,
    "unit_value" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "value" DECIMAL(18,4) NOT NULL DEFAULT 0,
    "custom_fields" JSONB NOT NULL DEFAULT '{}',
    "is_deleted" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "updated_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "item_assembly_lines_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "composite_item_components_organization_id_composite_item_id_idx" ON "composite_item_components"("organization_id", "composite_item_id");

-- CreateIndex
CREATE INDEX "composite_item_components_organization_id_component_item_id_idx" ON "composite_item_components"("organization_id", "component_item_id");

-- CreateIndex
CREATE INDEX "item_assemblies_organization_id_composite_item_id_assembly__idx" ON "item_assemblies"("organization_id", "composite_item_id", "assembly_date");

-- CreateIndex
CREATE INDEX "item_assemblies_organization_id_location_id_assembly_date_idx" ON "item_assemblies"("organization_id", "location_id", "assembly_date");

-- CreateIndex
-- ⚠️ REVIEW [ADD UNIQUE] fails on existing duplicates; remember soft-deleted rows still occupy their unique key
CREATE UNIQUE INDEX "item_assemblies_organization_id_assembly_number_key" ON "item_assemblies"("organization_id", "assembly_number");

-- CreateIndex
CREATE INDEX "item_assembly_lines_assembly_id_idx" ON "item_assembly_lines"("assembly_id");

-- CreateIndex
CREATE INDEX "item_assembly_lines_organization_id_item_id_lot_id_idx" ON "item_assembly_lines"("organization_id", "item_id", "lot_id");

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_composite_item_id_fkey" FOREIGN KEY ("composite_item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_component_item_id_fkey" FOREIGN KEY ("component_item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "composite_item_components" ADD CONSTRAINT "composite_item_components_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_composite_item_id_fkey" FOREIGN KEY ("composite_item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_composite_uom_id_fkey" FOREIGN KEY ("composite_uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_composite_lot_id_fkey" FOREIGN KEY ("composite_lot_id") REFERENCES "lots"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assemblies" ADD CONSTRAINT "item_assemblies_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_assembly_id_fkey" FOREIGN KEY ("assembly_id") REFERENCES "item_assemblies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "units_of_measurement"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_lot_id_fkey" FOREIGN KEY ("lot_id") REFERENCES "lots"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_lot_package_id_fkey" FOREIGN KEY ("lot_package_id") REFERENCES "lot_packages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "item_assembly_lines" ADD CONSTRAINT "item_assembly_lines_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateIndex (Partial Unique for composite components)
CREATE UNIQUE INDEX "composite_item_components_composite_component_key" ON "composite_item_components"("composite_item_id", "component_item_id") WHERE is_deleted = false;

-- CreateIndex (GIN on lots.parent_lot_ids)
CREATE INDEX "lots_parent_lot_ids_idx" ON "lots" USING GIN ("parent_lot_ids");

-- Enable RLS
ALTER TABLE "composite_item_components" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "item_assemblies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "item_assembly_lines" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_isolation" ON "composite_item_components"
  AS PERMISSIVE FOR ALL
  TO public
  USING ((organization_id = (current_setting('app.current_tenant_id'::text, true))::uuid));

CREATE POLICY "tenant_isolation" ON "item_assemblies"
  AS PERMISSIVE FOR ALL
  TO public
  USING ((organization_id = (current_setting('app.current_tenant_id'::text, true))::uuid));

CREATE POLICY "tenant_isolation" ON "item_assembly_lines"
  AS PERMISSIVE FOR ALL
  TO public
  USING ((organization_id = (current_setting('app.current_tenant_id'::text, true))::uuid));
