-- remove_bill_unique_constraint
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
-- DropIndex
DROP INDEX "bills_organization_id_bill_number_key";

-- DropIndex
DROP INDEX "permission_templates_organization_id_name_key";

-- DropIndex
DROP INDEX "roles_organization_id_name_key";
