-- link_bills_to_po
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
-- AlterTable
ALTER TABLE "bills" ADD COLUMN     "source_po_id" UUID;

-- AddForeignKey
ALTER TABLE "bills" ADD CONSTRAINT "bills_source_po_id_fkey" FOREIGN KEY ("source_po_id") REFERENCES "purchase_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;
