-- add_job_receipt_to_bill_item
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 15 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- AlterTable
ALTER TABLE "bill_items" ADD COLUMN     "job_receipt_id" UUID;

-- AddForeignKey
ALTER TABLE "bill_items" ADD CONSTRAINT "bill_items_job_receipt_id_fkey" FOREIGN KEY ("job_receipt_id") REFERENCES "job_receipts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
