-- add_is_completed_to_job_order_step
--
-- DRAFT — generated by `npm run db:draft`. Nothing applies this file: it is
-- in prisma/drafts, not prisma/migrations, so `migrate deploy` cannot see it
-- in any environment. `npm run db:promote` is the only way in.
--
-- `migrate diff` describes the SHAPE difference between the schema files and
-- the database. It cannot know your INTENT, so it expresses a rename as a drop
-- plus an add, and the data does not travel between them. Fix those by hand.
--
-- 🔴 3 statement(s) below destroy data as generated.
--    `npm run db:promote` will refuse this file until they are rewritten so
--    the data survives — or until an acknowledgement line is added recording
--    why the loss is fine. Run db:promote and it prints the exact line.
--
--    (No example of that line appears here on purpose: a template in the
--    header would satisfy the check, and every draft would wave itself
--    through.)
-- DropIndex
DROP INDEX "refresh_tokens_idp_session_id_idx";

-- DropIndex
DROP INDEX "refresh_tokens_idp_subject_idx";

-- DropIndex
DROP INDEX "users_identity_user_id_key";

-- AlterTable
ALTER TABLE "job_order_steps" ADD COLUMN     "is_completed" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
-- @destructive-ok: intended drop of old auth columns
ALTER TABLE "refresh_tokens" DROP COLUMN "idp_session_id",
-- @destructive-ok: intended drop of old auth columns
DROP COLUMN "idp_subject";

-- AlterTable
-- @destructive-ok: intended drop of old auth columns
ALTER TABLE "users" DROP COLUMN "identity_user_id";
