-- remove_job_issue_transport_columns
--
-- HAND-WRITTEN, not generated by `npm run db:draft`.
--
-- 🔴 `migrate diff` cannot be used to author against this database right now.
-- `20260810053834_composite_items` is applied but its file is not on disk, and
-- none of its tables are in prisma/schema, so every diff reads that feature as
-- drift and emits DROP TABLE for composite_item_components, item_assemblies and
-- item_assembly_lines plus 21 DROP CONSTRAINT. This file therefore contains only
-- the four statements this change actually needs; the composite-items divergence
-- is untouched and still has to be fixed separately.
--
-- The Issue dialog's Transport section is gone (2026-08-10): nothing captured
-- these four values, and the printed challan no longer renders them.
-- `transporter_id` is deliberately left in place — see JobIssue in
-- prisma/schema/jobwork.prisma.

-- @destructive-ok: the Issue dialog's Transport section was removed, so nothing writes vehicle_no, lr_no, lr_date or eway_bill_no; the challan and the issue detail no longer read them either, and any values already recorded are not worth a column each

ALTER TABLE "job_issues" DROP COLUMN "vehicle_no";
ALTER TABLE "job_issues" DROP COLUMN "lr_no";
ALTER TABLE "job_issues" DROP COLUMN "lr_date";
ALTER TABLE "job_issues" DROP COLUMN "eway_bill_no";
